/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-background": "#191c1e",
                "surface": "#f7f9fb",
                "background": "#f7f9fb",
                "primary-fixed": "#d8e2ff",
                "surface-container-high": "#e6e8ea",
                "outline": "#727785",
                "on-secondary": "#ffffff",
                "outline-variant": "#c2c6d6",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "tertiary-container": "#b75b00",
                "primary": "#0058be",
                "primary-container": "#2170e4",
                "secondary-container": "#b6ccff",
                "on-secondary-fixed-variant": "#304671",
                "tertiary-fixed": "#ffdcc6",
                "primary-fixed-dim": "#adc6ff",
                "surface-dim": "#d8dadc",
                "surface-variant": "#e0e3e5",
                "tertiary-fixed-dim": "#ffb786",
                "on-secondary-container": "#405682",
                "on-secondary-fixed": "#001a42",
                "error": "#ba1a1a",
                "inverse-on-surface": "#eff1f3",
                "on-surface-variant": "#424754",
                "secondary": "#495e8a",
                "surface-container": "#eceef0",
                "secondary-fixed-dim": "#b1c6f9",
                "on-tertiary-fixed": "#311400",
                "on-primary-fixed-variant": "#004395",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#001a42",
                "inverse-surface": "#2d3133",
                "surface-bright": "#f7f9fb",
                "on-tertiary-fixed-variant": "#723600",
                "on-error-container": "#93000a",
                "surface-tint": "#005ac2",
                "on-tertiary-container": "#fffbff",
                "tertiary": "#924700",
                "surface-container-highest": "#e0e3e5",
                "inverse-primary": "#adc6ff",
                "surface-container-low": "#f2f4f6",
                "on-tertiary": "#ffffff",
                "error-container": "#ffdad6",
                "on-surface": "#191c1e",
                "on-primary-container": "#fefcff",
                "secondary-fixed": "#d8e2ff",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            fontFamily: {
                headline: ["Manrope", "sans-serif"],
                body: ["Inter", "sans-serif"],
                label: ["Inter", "sans-serif"],
                manrope: ["Manrope", "sans-serif"],
                inter: ["Inter", "sans-serif"],
            },
        },
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries"),
    ],
};
